apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: administrators
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-configurator
rules:
- apiGroups: [""]
  resources: ["replicationcontrollers", "services", "deployments", "statefulsets"]
  verbs: ["create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewers
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "logs"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-access
rules:
- apiGroups: [""]
  resources: ["secrets", "namespaces"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developers
rules:
- apiGroups: [""]
  resources: ["deployments", "pods", "configmaps"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructure-team
rules:
- apiGroups: [""]
  resources: ["networkpolicies", "volumes", "nodes"]
  verbs: ["create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: business-analysts
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "logs"]
  verbs: ["get"]